# Generated by Django 4.0.4 on 2022-06-28 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('adp_formatted', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.draft')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='draft.owner')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.player')),
            ],
        ),
    ]
