# Generated by Django 4.0.4 on 2022-06-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
