# Generated by Django 4.0.4 on 2022-07-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_alter_player_player_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='Manager',
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['adp_formatted']},
        ),
        migrations.RenameField(
            model_name='draftpick',
            old_name='owner',
            new_name='manager',
        ),
    ]
