# Generated by Django 4.0.4 on 2022-07-16 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_rename_owner_manager_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='draft.draft'),
        ),
    ]
