# Generated by Django 4.0.4 on 2022-07-16 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_manager_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='budget',
            field=models.DecimalField(decimal_places=1, default=200.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='manager',
            name='draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managers', to='draft.draft'),
        ),
    ]
