# Generated by Django 4.0.4 on 2022-07-17 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_alter_draftpick_manager_alter_draftpick_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpick',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2022, 7, 17, 14, 37, 38, 444953, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
