# Generated by Django 4.0.4 on 2022-07-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0007_draftpick_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpick',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
