# Generated by Django 4.0.4 on 2022-07-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0008_alter_draftpick_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='draftpick',
            unique_together={('draft', 'player')},
        ),
    ]
