# Generated by Django 4.0.4 on 2022-07-17 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0009_alter_draftpick_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpick',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_managers', to='draft.manager'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='draft.draft'),
        ),
    ]
