# Generated by Django 4.0.4 on 2022-07-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0010_alter_draftpick_manager_alter_manager_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDraftPicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('manager', models.CharField(max_length=200)),
                ('draft_position', models.IntegerField()),
                ('position', models.CharField(max_length=10)),
                ('player', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
