# Generated by Django 4.0.4 on 2022-08-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0012_alter_historicaldraftpicks_options_draft_drafter'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpick',
            name='drafted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draftpick',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
