# Generated by Django 4.0.4 on 2022-08-03 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0013_draftpick_drafted_draftpick_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpick',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_managers', to='draft.manager'),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
