# Generated by Django 4.0.4 on 2022-08-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0014_alter_draftpick_manager_alter_draftpick_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='projected_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
