# Generated by Django 4.0.4 on 2022-08-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0015_player_projected_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='projected_draft',
            field=models.TextField(blank=True),
        ),
    ]
