# Generated by Django 4.0.4 on 2022-08-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0016_draft_projected_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='drafter',
            field=models.BooleanField(default=False),
        ),
    ]
