# Generated by Django 4.0.4 on 2022-08-14 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0017_manager_drafter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ('position',), 'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
        migrations.AddField(
            model_name='manager',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_players', to='draft.manager'),
        ),
    ]
