# Generated by Django 4.0.4 on 2022-08-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0018_alter_manager_options_manager_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='override_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
