# Generated by Django 4.0.4 on 2022-08-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0020_historicaldraftpicks_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('player_name', models.CharField(max_length=200)),
                ('fantasy_points', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pass_yards', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pass_tds', models.IntegerField()),
                ('rush_att', models.IntegerField()),
                ('rush_yards', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rush_tds', models.IntegerField()),
                ('receptions', models.IntegerField()),
                ('rec_yards', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rec_tds', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='historicaldraftpicks',
            name='result',
            field=models.CharField(choices=[('na', 'N/A'), ('great', 'Great'), ('good', 'Good'), ('ok', 'Ok'), ('bad', 'Bad'), ('injury', 'Injury'), ('handcuff', 'Handcuff')], default='na', max_length=200),
        ),
    ]
