# Generated by Django 4.0.4 on 2022-08-25 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0021_historicalplayerstats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplayerstats',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='draft.player'),
        ),
    ]
