# Generated by Django 4.0.4 on 2022-08-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0022_historicalplayerstats_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalplayerstats',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
