# Generated by Django 4.0.4 on 2022-08-25 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0023_historicalplayerstats_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldraftpicks',
            name='historical_stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='draft.historicalplayerstats'),
        ),
    ]
