# Generated by Django 4.0.4 on 2022-08-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0025_player_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalplayerstats',
            options={'ordering': ['-fantasy_points']},
        ),
        migrations.AddField(
            model_name='draft',
            name='saved_slots',
            field=models.TextField(blank=True),
        ),
    ]
