# Generated by Django 4.0.4 on 2022-08-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0026_alter_historicalplayerstats_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
