# Generated by Django 4.0.4 on 2022-08-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0027_draft_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='year',
            field=models.IntegerField(),
        ),
    ]
