# Generated by Django 4.0.4 on 2023-07-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0029_alter_historicaldraftpicks_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpick',
            name='draft_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
