# Generated by Django 4.0.4 on 2023-07-18 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0030_draftpick_draft_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftpick',
            name='watched',
        ),
        migrations.AddField(
            model_name='draftpick',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='WatchPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.draft')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_players', to='draft.manager')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_players', to='draft.player')),
            ],
            options={
                'unique_together': {('draft', 'player')},
            },
        ),
    ]
