# Generated by Django 4.0.4 on 2023-07-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0031_remove_draftpick_watched_draftpick_last_update_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='year',
            field=models.IntegerField(default=2022, max_length=4),
        ),
    ]
