# Generated by Django 4.0.4 on 2023-07-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0032_player_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftpick',
            name='draft_time',
        ),
    ]
