# Generated by Django 4.0.4 on 2023-07-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0033_remove_draftpick_draft_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('player_id', 'year')},
        ),
    ]
