# Generated by Django 4.0.4 on 2023-07-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0035_draft_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchpick',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
