# Generated by Django 4.0.4 on 2023-07-23 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0036_watchpick_watched'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftpick',
            options={'ordering': ('-last_update_time',)},
        ),
        migrations.CreateModel(
            name='BudgetPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(choices=[(0, 'QB'), (1, 'RB1'), (2, 'RB2'), (3, 'WR1'), (4, 'WR2'), (5, 'FLEX1'), (6, 'FLEX2'), (7, 'TE1'), (8, 'DEF1'), (9, 'BENCH1'), (10, 'BENCH2'), (11, 'BENCH3'), (12, 'BENCH4'), (13, 'BENCH5'), (14, 'BENCH6'), (15, 'BENCH7')], max_length=50)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.draft')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='draft.manager')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.player')),
            ],
        ),
    ]
