# Generated by Django 4.0.4 on 2023-07-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0037_alter_draftpick_options_budgetplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpick',
            name='position_slot',
            field=models.CharField(blank=True, choices=[(0, 'QB1'), (1, 'RB1'), (2, 'RB2'), (3, 'WR1'), (4, 'WR2'), (5, 'FLEX1'), (6, 'FLEX2'), (7, 'TE1'), (8, 'DEF1'), (9, 'BENCH1'), (10, 'BENCH2'), (11, 'BENCH3'), (12, 'BENCH4'), (13, 'BENCH5'), (14, 'BENCH6'), (15, 'BENCH7')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='budgetplayer',
            name='position',
            field=models.CharField(choices=[(0, 'QB1'), (1, 'RB1'), (2, 'RB2'), (3, 'WR1'), (4, 'WR2'), (5, 'FLEX1'), (6, 'FLEX2'), (7, 'TE1'), (8, 'DEF1'), (9, 'BENCH1'), (10, 'BENCH2'), (11, 'BENCH3'), (12, 'BENCH4'), (13, 'BENCH5'), (14, 'BENCH6'), (15, 'BENCH7')], max_length=50),
        ),
    ]
