# Generated by Django 4.0.4 on 2023-07-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0038_draftpick_position_slot_alter_budgetplayer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetplayer',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('budgeted', 'Budgeted'), ('drafted', 'Drafted')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
