# Generated by Django 4.0.4 on 2023-07-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0039_budgetplayer_status_alter_player_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='budget',
            field=models.FloatField(default=200),
        ),
    ]
