# Generated by Django 4.0.4 on 2023-08-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0040_alter_manager_budget'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchpick',
            unique_together={('draft', 'player', 'manager')},
        ),
    ]
