# Generated by Django 4.0.4 on 2023-08-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0041_alter_watchpick_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='early_season_schedule',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='playoff_weather_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
