# Generated by Django 4.0.4 on 2023-08-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0043_nflteam_remove_player_early_season_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteam',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
