# Generated by Django 4.0.4 on 2023-08-06 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0044_nflteam_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('week', models.IntegerField()),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matchup', to='draft.nflteam')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matchup', to='draft.nflteam')),
            ],
        ),
    ]
