# Generated by Django 4.0.4 on 2023-08-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0045_matchup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchup',
            options={'ordering': ['-year', 'week']},
        ),
        migrations.AddField(
            model_name='nflteam',
            name='defensive_ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
