# Generated by Django 4.0.4 on 2023-08-18 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0049_player_skepticism'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteam',
            name='early_season_def',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='early_season_qb',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='early_season_rb',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='early_season_te',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='early_season_wr',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
