# Generated by Django 4.0.4 on 2023-08-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0051_draft_starting_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteam',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
