# Generated by Django 4.0.4 on 2023-08-21 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0052_nflteam_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_assignments', to='draft.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
