# Generated by Django 4.0.4 on 2023-08-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0054_yearlynotes_remove_draft_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteam',
            name='playoff_schedule',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
