# Generated by Django 4.0.4 on 2023-08-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0055_nflteam_playoff_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteam',
            name='playoff_def',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='playoff_qb',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='playoff_rb',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='playoff_te',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='nflteam',
            name='playoff_wr',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
