# Generated by Django 4.0.4 on 2023-08-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0056_nflteam_playoff_def_nflteam_playoff_qb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='limit_def',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='draft',
            name='limit_qb',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='draft',
            name='limit_rb',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='draft',
            name='limit_te',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='draft',
            name='limit_wr',
            field=models.IntegerField(default=8),
        ),
    ]
