# Generated by Django 5.0.6 on 2024-06-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0057_draft_limit_def_draft_limit_qb_draft_limit_rb_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftpick',
            options={'ordering': ('player__adp_formatted',)},
        ),
        migrations.AlterField(
            model_name='budgetplayer',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgeted_players', to='draft.draft'),
        ),
        migrations.AlterField(
            model_name='budgetplayer',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgeted_players', to='draft.manager'),
        ),
        migrations.AlterField(
            model_name='budgetplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgeted_players', to='draft.player'),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafted_players', to='draft.draft'),
        ),
    ]
