# Generated by Django 5.0.6 on 2024-06-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0058_alter_draftpick_options_alter_budgetplayer_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='rounds',
            field=models.IntegerField(default=19),
        ),
    ]
