# Generated by Django 5.0.6 on 2024-07-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0060_alter_budgetplayer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetplayer',
            name='position_name',
            field=models.CharField(blank=True, choices=[('QB1', 'QB1'), ('RB1', 'RB1'), ('RB2', 'RB2'), ('WR1', 'WR1'), ('WR2', 'WR2'), ('FLEX1', 'FLEX1'), ('FLEX2', 'FLEX2'), ('TE1', 'TE1'), ('DEF1', 'DEF1'), ('BENCH1', 'BENCH1'), ('BENCH2', 'BENCH2'), ('BENCH3', 'BENCH3'), ('BENCH4', 'BENCH4'), ('BENCH5', 'BENCH5'), ('BENCH6', 'BENCH6'), ('BENCH7', 'BENCH7')], max_length=50, null=True),
        ),
    ]
