# Generated by Django 5.0.6 on 2024-07-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0061_budgetplayer_position_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetplayer',
            name='position',
        ),
    ]
