# Generated by Django 5.0.6 on 2024-07-13 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0062_remove_budgetplayer_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetplayer',
            old_name='position_name',
            new_name='position',
        ),
    ]
