# Generated by Django 5.0.6 on 2024-07-25 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0065_remove_draftpick_budget_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetplayer',
            name='position',
            field=models.CharField(blank=True, choices=[('QB1', 'QB1'), ('RB1', 'RB1'), ('RB2', 'RB2'), ('WR1', 'WR1'), ('WR2', 'WR2'), ('TE1', 'TE1'), ('FLEX1', 'FLEX1'), ('FLEX2', 'FLEX2'), ('DEF1', 'DEF1'), ('BENCH1', 'BENCH1'), ('BENCH2', 'BENCH2'), ('BENCH3', 'BENCH3'), ('BENCH4', 'BENCH4'), ('BENCH5', 'BENCH5'), ('BENCH6', 'BENCH6'), ('BENCH7', 'BENCH7')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='draftpick',
            name='position_slot',
            field=models.CharField(blank=True, choices=[('QB1', 'QB1'), ('RB1', 'RB1'), ('RB2', 'RB2'), ('WR1', 'WR1'), ('WR2', 'WR2'), ('TE1', 'TE1'), ('FLEX1', 'FLEX1'), ('FLEX2', 'FLEX2'), ('DEF1', 'DEF1'), ('BENCH1', 'BENCH1'), ('BENCH2', 'BENCH2'), ('BENCH3', 'BENCH3'), ('BENCH4', 'BENCH4'), ('BENCH5', 'BENCH5'), ('BENCH6', 'BENCH6'), ('BENCH7', 'BENCH7')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('type', models.CharField(choices=[('rushing', 'Rushing'), ('receiving', 'Receiving'), ('passing', 'Passing')], max_length=100)),
                ('age', models.IntegerField()),
                ('games', models.IntegerField()),
                ('games_started', models.IntegerField()),
                ('rush_attempts', models.IntegerField()),
                ('rush_yards', models.IntegerField()),
                ('targets', models.IntegerField()),
                ('receptions', models.IntegerField()),
                ('receiving_yards', models.IntegerField()),
                ('tds', models.IntegerField()),
                ('first_downs', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.player')),
            ],
        ),
    ]
