# Generated by Django 5.0.6 on 2024-07-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0066_alter_budgetplayer_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='first_downs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='games',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='games_started',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='receiving_yards',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='receptions',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='rush_attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='rush_yards',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='targets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='tds',
            field=models.IntegerField(null=True),
        ),
    ]
