# Generated by Django 5.0.6 on 2024-07-27 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0067_alter_playerstats_age_alter_playerstats_first_downs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='draft.player'),
        ),
    ]
