# Generated by Django 5.0.6 on 2024-08-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0068_alter_player_player_id_alter_playerstats_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
