# Generated by Django 5.0.6 on 2024-08-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0069_player_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionADP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=3)),
                ('adp', models.IntegerField()),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ('position', 'adp'),
            },
        ),
        migrations.AddField(
            model_name='player',
            name='wind_score',
            field=models.IntegerField(default=0, help_text='Wind at their back (Off/Def help)'),
        ),
    ]
