# Generated by Django 5.0.6 on 2024-08-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0070_positionadp_player_wind_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
