# Generated by Django 5.0.6 on 2024-08-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0072_player_adp_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bye_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
