# Generated by Django 5.0.6 on 2024-08-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0073_player_bye_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
