# Generated by Django 5.0.6 on 2024-08-10 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0074_player_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlanChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('QB1', 'QB1'), ('RB1', 'RB1'), ('RB2', 'RB2'), ('WR1', 'WR1'), ('WR2', 'WR2'), ('TE1', 'TE1'), ('FLEX1', 'FLEX1'), ('FLEX2', 'FLEX2'), ('DEF1', 'DEF1'), ('BENCH1', 'BENCH1'), ('BENCH2', 'BENCH2'), ('BENCH3', 'BENCH3'), ('BENCH4', 'BENCH4'), ('BENCH5', 'BENCH5'), ('BENCH6', 'BENCH6'), ('BENCH7', 'BENCH7')], max_length=50, null=True)),
                ('budget_pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.budgetplayer')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.draft')),
                ('draft_pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.draftpick')),
            ],
            options={
                'unique_together': {('draft', 'position')},
            },
        ),
    ]
