# Generated by Django 5.0.6 on 2026-07-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0075_draft_date_created_planchange"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="target_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prime", "Prime"),
                    ("starter", "Starter"),
                    ("streamer", "Streamer"),
                    ("sleeper", "Sleeper"),
                    ("catalyst", "Catalyst"),
                    ("undraftable", "Undraftable"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
