# Generated by Django 5.0.6 on 2026-08-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0077_draftplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="available_to_spectators",
            field=models.BooleanField(default=False),
        ),
    ]
