# Generated by Django 5.0.6 on 2026-08-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0078_draft_available_to_spectators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="favorite",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
