# Generated by Django 5.0.6 on 2026-08-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0080_favorite_false_to_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="target_tier",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
