# Generated by Django 5.0.6 on 2026-08-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0081_player_target_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="is_projection",
            field=models.BooleanField(default=False),
        ),
    ]
