# Generated by Django 5.0.6 on 2026-08-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0081_player_target_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="nflteam",
            name="coaching_impact",
            field=models.CharField(
                blank=True,
                choices=[("good", "Good"), ("bad", "Bad")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="defensive_impact",
            field=models.CharField(
                blank=True,
                choices=[("good", "Good"), ("bad", "Bad")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="has_injury",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="is_projection",
            field=models.BooleanField(default=False),
        ),
    ]
