# Generated by Django 5.0.6 on 2026-08-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0082_player_is_projection"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="has_injury",
            field=models.BooleanField(default=False),
        ),
    ]
