# Generated by Django 5.0.6 on 2026-08-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0082_nflteam_coaching_impact_player_defensive_impact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="my_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="my_price_rationale",
            field=models.TextField(blank=True, null=True),
        ),
    ]
