# Generated by Django 5.0.6 on 2026-08-11 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0083_player_my_price_player_my_price_rationale"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("starting_budget", models.IntegerField(default=200)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("last_update_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-year", "-date_created", "name"),
            },
        ),
        migrations.CreateModel(
            name="MockPick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_slot",
                    models.CharField(
                        choices=[
                            ("QB1", "QB1"),
                            ("RB1", "RB1"),
                            ("RB2", "RB2"),
                            ("WR1", "WR1"),
                            ("WR2", "WR2"),
                            ("TE1", "TE1"),
                            ("FLEX1", "FLEX1"),
                            ("FLEX2", "FLEX2"),
                            ("DEF1", "DEF1"),
                            ("BENCH1", "BENCH1"),
                            ("BENCH2", "BENCH2"),
                            ("BENCH3", "BENCH3"),
                            ("BENCH4", "BENCH4"),
                            ("BENCH5", "BENCH5"),
                            ("BENCH6", "BENCH6"),
                            ("BENCH7", "BENCH7"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.IntegerField(default=0)),
                ("last_update_time", models.DateTimeField(auto_now=True)),
                (
                    "mock_draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picks",
                        to="draft.mockdraft",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_picks",
                        to="draft.player",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("mock_draft", "player"),
                    ("mock_draft", "position_slot"),
                },
            },
        ),
        migrations.AddField(
            model_name="mockdraft",
            name="players",
            field=models.ManyToManyField(
                related_name="mock_drafts", through="draft.MockPick", to="draft.player"
            ),
        ),
    ]
