# Generated by Django 5.0.6 on 2026-08-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0083_player_has_injury"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="coaching_impact",
            field=models.CharField(
                blank=True,
                choices=[("good", "Good"), ("bad", "Bad")],
                max_length=10,
                null=True,
            ),
        ),
    ]
