# Generated by Django 5.0.6 on 2026-08-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0084_mockdraft_mockpick_mockdraft_players"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="years_experience",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
