# Generated by Django 5.0.6 on 2026-08-21 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0085_player_years_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="risk_score",
            field=models.PositiveIntegerField(
                default=0,
                help_text="1-10, higher = riskier. 0 = not reviewed yet.",
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="risk_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
