# Generated by Django 5.0.6 on 2026-08-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0086_player_risk_score_player_risk_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="adp_ffc",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="adp_fpros",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="adp_mfl",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="adp_source",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="fpros_id",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="mfl_id",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name="AdpSourceSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=16)),
                ("year", models.IntegerField()),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("feed_rows", models.IntegerField(default=0)),
                ("matched", models.IntegerField(default=0)),
                ("fuzzy_matched", models.IntegerField(default=0)),
                ("unmatched", models.IntegerField(default=0)),
                ("unmatched_names", models.TextField(blank=True, default="")),
                ("sample_size", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-year", "source"),
                "unique_together": {("source", "year")},
            },
        ),
    ]
