# Generated by Django 5.0.6 on 2026-08-27 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0087_player_adp_ffc_player_adp_fpros_player_adp_mfl_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdpPlayerAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(blank=True, default="", max_length=16)),
                ("feed_name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=10)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adp_aliases",
                        to="draft.player",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ADP player aliases",
                "ordering": ("feed_name",),
                "unique_together": {("source", "feed_name", "position")},
            },
        ),
    ]
