# Generated by Django 5.0.6 on 2026-09-04 18:44

import django.db.models.deletion
from django.db import migrations, models


def suffix_duplicate_plan_names(apps, schema_editor):
    """Make (year, name) unique before the constraint lands.

    Nothing stopped duplicates until now, and a live DB may hold some. The
    NEWEST plan of a colliding set keeps the name — that's the one a re-save
    would overwrite from here on — and the older ones get " (2)", " (3)" … in
    creation order, so no plan is lost.
    """
    DraftPlan = apps.get_model("draft", "DraftPlan")
    seen = {}
    for plan in DraftPlan.objects.order_by("year", "name", "-date_created", "-id"):
        key = (plan.year, plan.name)
        count = seen.get(key, 0) + 1
        seen[key] = count
        if count > 1:
            plan.name = f"{plan.name} ({count})"
            plan.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0092_replace_mfl_adp_with_sharks"),
    ]

    operations = [
        migrations.RunPython(
            suffix_duplicate_plan_names, migrations.RunPython.noop, elidable=True,
        ),
        migrations.AlterUniqueTogether(
            name="draftplan",
            unique_together={("year", "name")},
        ),
        migrations.CreateModel(
            name="DraftPlanBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_slot",
                    models.CharField(
                        choices=[
                            ("QB1", "QB1"),
                            ("RB1", "RB1"),
                            ("RB2", "RB2"),
                            ("WR1", "WR1"),
                            ("WR2", "WR2"),
                            ("TE1", "TE1"),
                            ("FLEX1", "FLEX1"),
                            ("FLEX2", "FLEX2"),
                            ("DEF1", "DEF1"),
                            ("BENCH1", "BENCH1"),
                            ("BENCH2", "BENCH2"),
                            ("BENCH3", "BENCH3"),
                            ("BENCH4", "BENCH4"),
                            ("BENCH5", "BENCH5"),
                            ("BENCH6", "BENCH6"),
                            ("BENCH7", "BENCH7"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rank", models.IntegerField()),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backups",
                        to="draft.draftplan",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_backups",
                        to="draft.player",
                    ),
                ),
            ],
            options={
                "ordering": ("position_slot", "rank"),
                "unique_together": {
                    ("plan", "position_slot", "player"),
                    ("plan", "position_slot", "rank"),
                },
            },
        ),
        migrations.CreateModel(
            name="MockBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_slot",
                    models.CharField(
                        choices=[
                            ("QB1", "QB1"),
                            ("RB1", "RB1"),
                            ("RB2", "RB2"),
                            ("WR1", "WR1"),
                            ("WR2", "WR2"),
                            ("TE1", "TE1"),
                            ("FLEX1", "FLEX1"),
                            ("FLEX2", "FLEX2"),
                            ("DEF1", "DEF1"),
                            ("BENCH1", "BENCH1"),
                            ("BENCH2", "BENCH2"),
                            ("BENCH3", "BENCH3"),
                            ("BENCH4", "BENCH4"),
                            ("BENCH5", "BENCH5"),
                            ("BENCH6", "BENCH6"),
                            ("BENCH7", "BENCH7"),
                        ],
                        max_length=50,
                    ),
                ),
                ("rank", models.IntegerField()),
                ("last_update_time", models.DateTimeField(auto_now=True)),
                (
                    "mock_draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backups",
                        to="draft.mockdraft",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_backups",
                        to="draft.player",
                    ),
                ),
            ],
            options={
                "ordering": ("position_slot", "rank"),
                "unique_together": {
                    ("mock_draft", "position_slot", "player"),
                    ("mock_draft", "position_slot", "rank"),
                },
            },
        ),
    ]
