# Generated by Django 5.0.6 on 2026-09-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0093_plan_and_mock_backups"),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="target_def",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="draft",
            name="target_qb",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="draft",
            name="target_rb",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="draft",
            name="target_te",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="draft",
            name="target_wr",
            field=models.IntegerField(default=0),
        ),
    ]
