# Generated by Django 5.0.6 on 2026-09-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0093_plan_and_mock_backups"),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="target_bench",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="draft",
            name="target_other",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="draft",
            name="target_rb",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="draft",
            name="target_rb_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="draft",
            name="target_wr",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="draft",
            name="target_wr_count",
            field=models.IntegerField(default=0),
        ),
    ]
