# Generated by Django 5.0.6 on 2026-09-19 18:22

from django.db import migrations, models


def carry_locked_into_protected(apps, schema_editor):
    """Every draft flagged `locked` today meant "don't delete me".

    That meaning moves to `protected`; `locked` keeps its rows and takes on its
    new meaning (picks frozen), which is right for these: they are finished
    drafts, and freezing them is what you'd tick anyway.
    """
    Draft = apps.get_model("draft", "Draft")
    Draft.objects.filter(locked=True).update(protected=True)


class Migration(migrations.Migration):

    dependencies = [
        ("draft", "0094_draft_target_bench_draft_target_other_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="protected",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            carry_locked_into_protected,
            # Reversing drops the new column, so there is nothing to undo.
            migrations.RunPython.noop,
        ),
    ]
