# Generated by Django 4.0.4 on 2022-05-14 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('baseobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rules.baseobject')),
                ('name', models.CharField(max_length=200, verbose_name='Rule Name')),
                ('short_name', models.CharField(max_length=50, verbose_name='Rule Short Name')),
                ('result', models.CharField(choices=[('pass', 'PASS'), ('not', 'NO PASS')], max_length=50, verbose_name='Result')),
            ],
            bases=('rules.baseobject',),
        ),
        migrations.CreateModel(
            name='RuleDecision',
            fields=[
                ('baseobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rules.baseobject')),
                ('decision', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=50, verbose_name='Decision')),
                ('rule_to_decide', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='rules.rule', verbose_name='Rule')),
            ],
            bases=('rules.baseobject',),
        ),
    ]
